class GPT:
    def __init__(self, name, category, description, source):
        self.name = name
        self.category = category
        self.description = description
        self.source = source

    def __str__(self):
        return f"{self.name} ({self.category}): {self.description} - Source: {self.source}"

# List of GPTs
gpts = [
    # Existing GPTs
    GPT("DALL·E", "Writing", "Transform your ideas into amazing images", "ChatGPT"),
    GPT("Consensus", "Research & Analysis", "Your AI Research Assistant. Search 200M academic papers.", "Consensus"),
    GPT("Code Tutor", "Programming", "Helps in coding with guidance.", "Khan Academy"),
    GPT("Books", "Lifestyle", "Your AI guide in the world of literature and reading.", "Josh Brent N. Villocido"),
    GPT("AllTrails", "Lifestyle", "Find trails that fit your nature for your next hike, ride, or run.", "alltrails.com"),
    GPT("Ai PDF", "Productivity", "Handles PDF documents up to 2GB per file, allows 1000s of PDF uploads.", "myaidrive.com"),
    GPT("Grimoire", "Programming", "Coding Wizard🧙‍♂️ Create a website or anything with a sentence.", "gptavern.mindgoblinstudios.com"),
    GPT("Canva", "Productivity", "Effortlessly design anything: presentations, logos, social media posts and more.", "canva.com"),
    GPT("AskYourPDF Research Assistant", "Research & Analysis", "Chat with multiple files, generate articles with citations, analyze and generate references for papers.", "askyourpdf.com"),
    GPT("Logo Creator", "Design", "Generate professional logo designs and app icons.", "Chase Lean"),
    GPT("WebPilot", "Productivity", "Browse, Write & Agent, API Offering", "webpilot.ai"),
    GPT("DesignerGPT", "Design", "Creates and hosts beautiful websites", "Pietro Schirano"),
    GPT("ScholarAI", "Research & Analysis", "AI Scientist - generate new hypotheses, analyze text, figures, and tables from 200M+ research papers and books", "scholarai.io"),
    GPT("GPT Finder", "Productivity", "Discover the best Custom GPT at OpenAI's GPT Store", "NAIF J ALOTAIBI"),
    GPT("22.500+ Best Custom GPTs", "Productivity", "Search all public GPTs in one place. Find the best Custom ChatGPTs tailored to your needs.", "seo.ai"),
    GPT("VideoGPT by VEED", "Media", "The easy way to generate stunning videos and grow your audience with AI (beta).", "veed.io"),
    GPT("Data Analyst", "Programming", "Drop in any files and I can help analyze and visualize your data.", "ChatGPT"),
    GPT("Hot Mods", "Lifestyle", "Let's modify your image into something really wild.", "ChatGPT"),
    GPT("Creative Writing Coach", "Writing", "I'm eager to read your work and give you feedback to improve your skills.", "ChatGPT"),
    GPT("Coloring Book Hero", "Lifestyle", "Take any idea and turn it into whimsical coloring book pages.", "ChatGPT"),
    GPT("Planty", "Lifestyle", "I'm Planty, your fun and friendly plant care assistant! Ask me how to best take care of your plants.", "ChatGPT"),
    GPT("ChatGPT Classic", "General", "The latest version of GPT-4 with no additional capabilities.", "ChatGPT"),
    GPT("Web Browser", "Productivity", "I can browse the web to help you gather information or conduct research", "ChatGPT"),
    GPT("Game Time", "Lifestyle", "I can quickly explain board games or card games to players of any age. Let the games begin!", "ChatGPT"),
    GPT("The Negotiator", "Lifestyle", "I'll help you advocate for yourself and get better outcomes. Become a great negotiator.", "ChatGPT"),
    GPT("Cosmic Dream", "Art", "Visionary painter of digital wonder.", "ChatGPT"),
    GPT("Tech Support Advisor", "Productivity", "From setting up a printer to troubleshooting a device, I’m here to help you step-by-step.", "ChatGPT"),
    GPT("Laundry Buddy", "Lifestyle", "Ask me anything about stains, settings, sorting and everything laundry.", "ChatGPT"),
    GPT("Sous Chef", "Lifestyle", "I’ll give you recipes based on the foods you love and ingredients you have.", "ChatGPT"),
    GPT("Math Mentor", "Education", "I help parents help their kids with math. Need a 9pm refresher on geometry proofs? I’m here for you.", "ChatGPT"),
    GPT("Mocktail Mixologist", "Lifestyle", "I’ll make any party a blast with mocktail recipes with whatever ingredients you have on hand.", "ChatGPT"),
    GPT("genz 4 meme", "Entertainment", "i help u understand the lingo & the latest memes.", "ChatGPT"),
       GPT("LogoGPT", "Design", "Designs personalized logos from sketches.", "A SAI RAHUL"),
    GPT("Image Edit, Copying & Merge", "Design", "Replicate Image, Images Merge, Image Edit, Style Transfer.", "neural.love"),
    GPT("Glibatree Art Designer", "Art", "Turn any idea into FOUR unique and beautiful variations.", "glibatree.com"),
    GPT("Cartoonize Yourself", "Lifestyle", "Turns photos into Pixar-style illustrations.", "karenxcheng.com"),
    GPT("Gerry, The Logo Designer", "Design", "Boost your Startup with unique, creative Logos!", "Filippo Iwan Cappiello"),
    GPT("Logo Maker", "Design", "Makes you a professional high quality PNG for your business", "Andrew Gao"),
    GPT("Photo Multiverse", "Design", "Upload your photo for a DALL·E 3 version then customize your background world!", "sablevista.com"),
    GPT("スーパーロゴデザイナ「ロゴ作る君」", "Design", "あなたのお店のロゴデザインを爆速で作ってくれる頼りになる存在です。", "TOMOYUKI ENOMOTO"),
    GPT("Write For Me", "Writing", "Write tailored, engaging content with a focus on quality, relevance and precise word count.", "puzzle.today"),
    GPT("Fully SEO Optimized Article", "Writing", "Create a 100% Unique, Plagiarism Free Content with SEO Optimization.", "Muhammad Talha"),
    GPT("超级论文辅助", "Education", "提出你的论文主题, 我将为你提供论文大纲.", "autogen.icu"),
    GPT("超级写作大师", "Writing", "根据引导能更好的写任何文章", "autogen.icu"),
    GPT("All-around Writer", "Writing", "A professional writer specialized in various content types.", "Kevin Ivery"),
    GPT("Automated Blog Post Writer", "Writing", "Craft professionally written, and researched blog posts.", "octaneai.com"),
    GPT("Academic Assistant Pro", "Education", "Professional academic assistant with a professorial touch", "Kevin Ivery"),
    GPT("论文润色大师", "Education", "优化学术论文，提供编辑和说明。", "sdfearhbart"),
    GPT("Income Stream Surfer's SEO Content Writer", "Writing", "Writes SEO Content using ChatGPT For ANY website", "incomestreamsurfers.com"),
    GPT("ChatPRD", "Productivity", "An on-demand Chief Product Officer for product management.", "chatprd.ai"),
    GPT("大学论文写作大师", "Education", "专业的大学中文论文写作大师", "xtxian.com"),
    GPT("FREE SEO Blog Content Outline Creator", "Writing", "FREE SEO Blog Content Outline Creator/Generator AI SEO Tool", "juliangoldie.com"),
    GPT("Diagrams: Show Me", "Productivity", "Diagrams, Architecture Visualisations, Flow-Charts, Mind Maps, Schemes.", "helpful.dev"),
    GPT("Doc Maker", "Productivity", "Prompt to create documents like resumes, reports, presentations, data sheets.", "aidocmaker.com"),
    GPT("Convert Anything", "Productivity", "The ultimate file converter for images, audio, video, documents and more.", "Pietro Schirano"),
    GPT("Professor Synapse", "Productivity", "Guide and facilitate goal achievement by summoning expert agents", "Joseph Rosenbaum"),
    GPT("Calendar GPT", "Productivity", "Helps you prepare for your day!", "zapier.com"),
    GPT("GPT Finder", "Productivity", "Helps you find the ideal GPT for your needs", "YOTA ISHIKAWA"),
    GPT("Prompty", "Productivity", "Your personal prompt engineer.", "Daniel Juhl"),
    GPT("GPT Public Directory", "Productivity", "A directory assistant for finding and registering GPTs.", "Geoffrey Robichaux"),
    GPT("Keymate.AI GPT", "Productivity", "Helps you search the web with Google, archive discoveries.", "keymate.ai"),
    GPT("Automation Consultant by Zapier", "Productivity", "Discover opportunities to save time with automation at work.", "zapier.com"),
    GPT("AskYourPDF Research Assistant", "Research & Analysis", "Enhance your research with the AskYourPDF Research Assistant.", "askyourpdf.com"),
    GPT("ScholarAI", "Research & Analysis", "AI Scientist - generate new hypotheses, analyze text, figures, and tables.", "scholarai.io"),
    GPT("Paper Interpreter", "Education", "論文のURLかPDFを入力すると、内容を日本語で分かりやすく説明します。", "daichikonno.jp"),
    GPT("AutoExpert (Academic)", "Education", "Provides a concise analysis covering a research paper's key aspects.", "llmimagineers.com"),
    GPT("VC Associate", "Business", "Pitch your startup and get a downloadable investment memo.", "Yohei Nakajima"),
    GPT("Video Insights", "Research & Analysis", "Chat with any video or audio for high-quality search, summarization, insights.", "videoinsights.ai"),
    GPT("Scholar GPT", "Research & Analysis", "Enhance research with 200M+ resources and built-in critical reading skills.", "awesomegpts.ai"),
    GPT("SEO", "Research & Analysis", "Enter any URL and keyword for an On-Page SEO analysis & insights!", "orrenprunckun.com"),
    GPT("Content Helpfulness and Quality SEO Analyzer", "Research & Analysis", "Evaluates web content helpfulness, relevance, and quality for targeted queries.", "Aleyda Solis"),
    GPT("Finance Wizard", "Finance", "Predicts future stock market prices and provides trading analysis.", "titantrades.com"),
    GPT("CrewAI Assistant", "Programming", "Python expert.", "JOAO M DURAES MOURA"),
    GPT("Screenshot To Code GPT", "Programming", "Upload a screenshot of a website and convert it to clean HTML/Tailwind/JS code.", "godofprompt.ai"),
    GPT("API Docs", "Programming", "OpenAI API, GPTs, Documentation and CookBook", "webpilot.ai"),
    GPT("Java Assistant", "Programming", "A Java code assistant and debugger.", "guliucang.com"),
    GPT("GPT Customizer, File Finder & JSON Action Creator", "Programming", "Customizes GPTs with file finding, action creation, and troubleshooting.", "webcafesoftware.com"),
    GPT("Flowbite GPT", "Programming", "Create websites using the UI components from Flowbite based on Tailwind CSS", "flowbite.com"),
    GPT("Code Guru", "Programming", "Reviews code, writes pull requests, generates and optimizes functions.", "Ryan J Topps"),
    GPT("Unreal Engine 5 Expert", "Programming", "Guide to UE5 Game Development Using Blueprints or C++", "artificial-nightmares.com"),
    GPT("Mr. Ranedeer", "Education", "Personalized AI tutor for various subjects.", "mr-ranedeer.com"),
    GPT("Universal Primer", "Education", "Learn everything about anything.", "runway.com"),
    GPT("Video Summarizer AI", "Education", "Generate educational summaries from lengthy videos.", "Klym Zhuravlov-Iuzefovych"),
    GPT("AI Tutor", "Education", "AI tutor skilled in guiding students through academic queries.", "techwithanirudh.com"),
    GPT("Math Solver", "Education", "Advanced math solver offering step-by-step solutions.", "studyx.ai"),
    GPT("AlphaNotes GPT", "Education", "Transforms videos or web articles into personal study aids.", "davideai.dev"),
    GPT("MBA Admission Consultant", "Education", "Assists in MBA admission process including profile reviews.", "jenova.ai"),
    GPT("Mr. Ranedeer Config Wizard", "Education", "Configuration wizard for Mr. Ranedeer.", "mr-ranedeer.com"),
    GPT("AI GPT", "Education", "Expert in AI & ML, adept in deep learning frameworks.", "Andrew Gao"),
    GPT("Prompt Professor", "Education", "Expert in Prompt Engineering.", "YOTA ISHIKAWA"),
    GPT("Math AI", "Education", "Advanced AI-powered guide for solving complex math problems.", "gptfinder.co"),
    GPT("Effortless Book Summary", "Education", "Provides quick book insights and overviews.", "Alberto Marcos"),
    GPT("Tattoo GPT", "Lifestyle", "Designs tattoos and offers customization options.", "Michael Moncada"),
    GPT("Astrology Birth Chart GPT", "Lifestyle", "Expert astrologer providing insights based on birth info.", "Dalexa Limited"),
    GPT("What should I watch?", "Lifestyle", "Recommends movies and TV shows based on preferences.", "ammaar.me"),
    GPT("DeepGame", "Entertainment", "Interactive story game with AI-generated images.", "UtileLabs"),
    GPT("GPT Shop Keeper", "Productivity", "Unofficial GPT App Store.", "gptavern.mindgoblinstudios.com"),
    GPT("Home Style Advisor", "Lifestyle", "Analyzes home photos for decor and style suggestions.", "Eric Rafael Ramos Suárez"),
    GPT("Rizz GPT", "Lifestyle", "Dating advice and assistance.", "6hive.ee"),
    GPT("Chinese BaZi Fortune Teller", "Lifestyle", "AI expert in BaZi astrology, offering traditional Chinese insights.", "structifi.com"),
    GPT("GymStreak Workout Creator", "Health", "Automatically creates home and gym workouts.", "gymstreak.com"),
    GPT("轻松阅读", "Education", "Generates article summaries and mind maps from links.", "autogen.icu"),
    GPT("GPTavern", "Entertainment", "A tavern of AI agents for various needs.", "gptavern.mindgoblinstudios.com"),
    
  ]
Function to display all GPTs
def display_gpts():
for gpt in gpts:
print(gpt)

Example usage
display_gpts()

